<b>Neden Numpy?</b>

In [1]:
a=[1,2,3,4]
b=[2,3,4,5]

In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])

In [6]:
a*b

array([ 2,  6, 12, 20])

<b>Numpy Array Oluşturmak</b>

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
a=np.array([1,2,3,4,5])

In [10]:
type(a)

numpy.ndarray

In [13]:
np.array([1.3, 9, 5.6, 7])

array([1.3, 9. , 5.6, 7. ])

In [12]:
np.array([1.3, 9, 5.6, 7], dtype="int")

array([1, 9, 5, 7])

<b>Sıfırdan array oluşturmak</b>

In [14]:
np.zeros(10) #sıfırlardan oluşan dizi tanımlama

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones((3,5)) #birlerden oluşan dizi tanımlama

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.full((3,3), 5) #3x3 lük 5'lerden oluşan dizi tanımlama

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [17]:
np.arange(0,31,3) #0-31 arasında 3er 3er artan sayıları getirme

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [18]:
np.linspace(0,1,10) #0-1 arasını 10'a bölme ve getirme

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.random.normal(10,4,(3,4)) #random 3x4 lük ortalaması 10, standart sapması 4 olan matris oluşturma

array([[ 3.0771831 , 11.35962819, 10.63029735,  6.16919709],
       [12.76862626,  9.07331505, 10.36117363, 16.14107254],
       [ 7.80374652, 17.64188756,  2.3036673 ,  6.41873899]])

In [20]:
np.random.randint(0,10, (3,3)) #3x3 lük int değerli 0-10 arası rasgele sayılar getirir

array([[0, 1, 4],
       [9, 7, 6],
       [0, 0, 1]])

<b>Özellikleri<b/><br>
<ul>
    <li>ndim: boyut sayısı</li>
    <li>shape: boyut bilgisi</li>
    <li>size: toplam eleman sayısı</li>
    <li>dtype: array veri tipi</li>
</ul>


In [21]:
import numpy as np

In [22]:
np.random.randint(10, size=10) #0-10 arası 10 karakterli int tipinde array oluşturdu

array([7, 8, 4, 9, 7, 5, 5, 6, 4, 1])

In [23]:
x=np.random.randint(10, size=10)

In [24]:
x.ndim

1

In [25]:
x.shape

(10,)

In [26]:
x.size

10

In [27]:
x.dtype

dtype('int32')

In [28]:
y=np.random.randint(10, size=(3,5))

In [29]:
y

array([[1, 5, 7, 9, 3],
       [5, 7, 0, 3, 4],
       [4, 4, 2, 0, 8]])

In [30]:
y.ndim

2

In [31]:
y.shape

(3, 5)

In [32]:
y.size

15

In [34]:
y.dtype

dtype('int32')

In [96]:
np.random.randint(10, size=(3,3,2)) #size=(3,3,2)--> 3 tane 3x2 lik matris

array([[[6, 1],
        [7, 8],
        [4, 1]],

       [[3, 1],
        [1, 7],
        [3, 7]],

       [[0, 9],
        [9, 2],
        [6, 4]]])

In [98]:
5*np.array([1,2,3]) #elemanların her birini 5 ile çarptı

array([ 5, 10, 15])

<b>Yeniden Şekillendirme - Reshaping</b>

In [35]:
np.arange(1,10) #1'den 10'a kadar olan sayılardan oluşan array oluşturur

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(1,10).reshape((3,3)) #3x3'ük matris haline getirdi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
z=np.arange(1,10)

In [45]:
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
z.ndim

1

In [42]:
q=z.reshape((1,9)) #1x9'luk matris haline geldi yani boyutu 2'ye çıktı

In [44]:
q

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
q.ndim

2

<b>Array Birleştirme - Concatenation</b>

In [47]:
import numpy as np

In [48]:
x=np.array([1,2,3])

In [49]:
y=np.array([4,5,6])

In [50]:
np.concatenate([x,y]) #arrayleri birleştirdi

array([1, 2, 3, 4, 5, 6])

In [52]:
a=np.array([[1,2,3], 
            [4,5,6]])

In [53]:
np.concatenate([a,a]) #iki matrisi birleştirdi

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.concatenate([a,a], axis=1) #axis birleştirmeyi satır yada sütun bazında yapılacağını belirler. 0-->satır; 1-->sütun

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

<b>Array Ayırma - Splitting</b>

In [55]:
import numpy as np

In [56]:
x=np.array([1,2,3,99,99,3,2,1])

In [57]:
np.split(x, [3,5]) #ilk 3, sonra ilk 5 ve geri kalanı da ayrı olmak üzere üç arraya böldü

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [58]:
a,b,c=np.split(x, [3,5]) #bölünmüş arrayleri a,b,c ye atadı

In [59]:
a

array([1, 2, 3])

In [60]:
b

array([99, 99])

In [61]:
c

array([3, 2, 1])

In [63]:
m=np.arange(16).reshape(4,4) #4x4 lük 1-16 arası sayıları sırayla bir matrise yazdırdı
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.vsplit(m, [2]) #2. satıra kadar olanları böldü

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [66]:
ust, alt=np.vsplit(m, [2])

In [67]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [68]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [70]:
sol, sag=np.hsplit(m, [2])

In [71]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [72]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

<b>Array Sıralama - sorting</b>

In [73]:
import numpy as np

In [75]:
v=np.array([2,5,1,6,4,9])
v

array([2, 5, 1, 6, 4, 9])

In [76]:
np.sort(v) #küçükten büyüğe sıralamış olduk

array([1, 2, 4, 5, 6, 9])

In [77]:
v

array([2, 5, 1, 6, 4, 9])

In [79]:
v.sort() #nu şekilde de yapılabilir
v

array([1, 2, 4, 5, 6, 9])

In [83]:
s=np.random.normal(20,5, (3,3))
s

array([[15.4929642 , 17.41364129, 18.41891612],
       [13.59271871, 11.16060012, 27.46769132],
       [28.67514087, 18.78013467, 23.11498171]])

In [84]:
np.sort(s, axis=1) #satırları sıraladı

array([[15.4929642 , 17.41364129, 18.41891612],
       [11.16060012, 13.59271871, 27.46769132],
       [18.78013467, 23.11498171, 28.67514087]])

In [85]:
np.sort(s, axis=0) #sütunları sıraladı

array([[13.59271871, 11.16060012, 18.41891612],
       [15.4929642 , 17.41364129, 23.11498171],
       [28.67514087, 18.78013467, 27.46769132]])

<b>İndex ile elemanlara erişmek</b>

In [1]:
import numpy as np

In [3]:
a=np.random.randint(10, size=10)
a

array([1, 9, 1, 8, 9, 9, 4, 0, 8, 0])

In [4]:
a[0]

1

In [5]:
a[-1]

0

In [6]:
a[0]=100
a

array([100,   9,   1,   8,   9,   9,   4,   0,   8,   0])

In [7]:
b=np.random.randint(10, size=(3,5))
b

array([[1, 5, 6, 3, 8],
       [2, 2, 3, 7, 8],
       [7, 7, 9, 7, 6]])

In [8]:
b[0][0]

1

In [10]:
b[0][4]=2.2 #int olarak kabul etti
b

array([[1, 5, 6, 3, 2],
       [2, 2, 3, 7, 8],
       [7, 7, 9, 7, 6]])

<b>Array alt küme ile elemanlara erişmek - Slicing</b>

In [11]:
import numpy as np

In [13]:
x=np.arange(20,30)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
x[0:3]

array([20, 21, 22])

In [15]:
x[:3]

array([20, 21, 22])

In [16]:
x[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [17]:
x[1::2] #ikişer ikişer artmasını sağladı

array([21, 23, 25, 27, 29])

In [18]:
x[0::3] #0. indexten başlayıp 3'er 3'er artır

array([20, 23, 26, 29])

In [20]:
y=np.random.randint(10, size=(5,5))
y

array([[3, 7, 9, 1, 9],
       [8, 4, 6, 4, 0],
       [8, 5, 2, 5, 0],
       [9, 3, 5, 2, 9],
       [8, 3, 7, 0, 6]])

In [21]:
y[:,0] #tüm satırları seç, sütunların sadece ilk indisini al

array([3, 8, 8, 9, 8])

In [22]:
y[0,:]

array([3, 7, 9, 1, 9])

In [23]:
y[0]

array([3, 7, 9, 1, 9])

In [26]:
y[0:2, 0:3]

array([[3, 7, 9],
       [8, 4, 6]])

In [30]:
y[:,0:2]

array([[3, 7],
       [8, 4],
       [8, 5],
       [9, 3],
       [8, 3]])

In [31]:
y[1:3, 0:2]

array([[8, 4],
       [8, 5]])

<b>Alt küme üzerinde işlem yapmak</b>

In [32]:
import numpy as np

In [33]:
a=np.random.randint(10, size=(5,5))
a

array([[3, 7, 0, 2, 5],
       [0, 3, 1, 4, 4],
       [7, 5, 5, 5, 5],
       [3, 4, 4, 2, 3],
       [6, 3, 0, 8, 2]])

In [35]:
a_alt=a[0:3, 0:2]
a_alt

array([[3, 7],
       [0, 3],
       [7, 5]])

In [37]:
a_alt[0,0]=9999
a_alt[1,1]=888
a_alt

array([[9999,    7],
       [   0,  888],
       [   7,    5]])

In [38]:
a #değişiklik bunu etkiledi biz bunu istemiyoruz

array([[9999,    7,    0,    2,    5],
       [   0,  888,    1,    4,    4],
       [   7,    5,    5,    5,    5],
       [   3,    4,    4,    2,    3],
       [   6,    3,    0,    8,    2]])

In [41]:
a_alt2=a[0:3, 0:2].copy() #bağımsız bir kopyasını oluşturdu
a_alt2

array([[9999,    7],
       [   0,  888],
       [   7,    5]])

In [43]:
a_alt2[0,0]=3333
a_alt2[1,1]=777
a_alt2

array([[3333,    7],
       [   0,  777],
       [   7,    5]])

In [44]:
a #ana arrayde değişiklik olmadı

array([[9999,    7,    0,    2,    5],
       [   0,  888,    1,    4,    4],
       [   7,    5,    5,    5,    5],
       [   3,    4,    4,    2,    3],
       [   6,    3,    0,    8,    2]])

<b>Fancy index ile elemanlara erişmek</b>

In [45]:
import numpy as np

In [47]:
z=np.arange(0, 30, 3) #0 dan 30 a kadar 3 er 3 er artır
z

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [48]:
getir=[1,3,5]

In [49]:
z[getir] #arrayin 1,3,5 inci indexlerini getirdi

array([ 3,  9, 15])

In [50]:
q=np.arange(9).reshape((3,3))
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [54]:
q[satir, sutun] #seçilen satır ve sütunu getirdi

array([1, 5])

In [55]:
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
q[0, [1, 2]] #0. satırın 1. ve 2. indexlerini getirdi

array([1, 2])

In [57]:
q[0:, [1, 2]] #tüm satırların 1. ve 2. indexlerini getirdi

array([[1, 2],
       [4, 5],
       [7, 8]])

<b>Koşullu eleman işlemleri</b>

In [58]:
import numpy as np

In [60]:
y=np.array([1,2,3,4,5])

In [61]:
y>3

array([False, False, False,  True,  True])

In [62]:
y[y>3] #bu şartı sağlayan elemanları getirdi

array([4, 5])

In [63]:
y*2

array([ 2,  4,  6,  8, 10])

<b>Matematiksel İşlemler</b>

In [64]:
import numpy as np

In [65]:
m=np.array([1,2,3,4,5])

In [66]:
m-1 #dizideki tüm elemanlara uygular

array([0, 1, 2, 3, 4])

In [68]:
np.subtract(m, 1) #tüm elemanlardan bir çıkaran fonksiyon

array([0, 1, 2, 3, 4])

In [71]:
np.add(m, 1) #tüm elemanları 1 ile toplar

array([2, 3, 4, 5, 6])

In [73]:
np.multiply(m, 4) # tüm elemanları 4 ile çarpar

array([ 4,  8, 12, 16, 20])

In [75]:
np.divide(m, 3) # tüm elemanları 3 ile böler

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [76]:
np.power(m, 3) #tüm elemanların 3. kuvvetini alır

array([  1,   8,  27,  64, 125], dtype=int32)

In [77]:
np.mod(m, 2) #2 ye bölümlerden kalanları getirdi

array([1, 0, 1, 0, 1], dtype=int32)

In [78]:
np.absolute(np.array([-3])) #mutlak değer alır

array([3])

In [79]:
np.sin(360) #sinüs hesabı

0.9589157234143065

In [80]:
np.log(m) #logaritma alma

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [81]:
?np #merak ettiklerimiz hakkında bilgi bulamk örneğin için googlea "numpy mathametics cheat sheet" dememiz yeterli

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Kader\\anaconda3\\envs\\tf-gpu\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\kader\anaconda3\envs\tf-gpu\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than

In [83]:
np.mean(m, axis=0) #array in ortalamasını verdi

3.0

In [84]:
m.sum() #içindeki elemanları topladı

15

In [85]:
m.min() #içindeki min. elemanı getirdi

1

<b>Numpy ile iki bilinmeyenli denkelm çözümü</b>

In [86]:
import numpy as np

5*x0+x1=12 <br>
x0+3*z1=10

In [89]:
a=np.array([[5, 1], [1, 3]]) #bilinmeyenlerin katsayılarını yazdım
b=np.array([12, 10])

In [90]:
a

array([[5, 1],
       [1, 3]])

In [91]:
b

array([12, 10])

In [92]:
x=np.linalg.solve(a, b) #denklem çözümü
x

array([1.85714286, 2.71428571])

<b>PANDAS SERİSİ OLUŞTURMA</b>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
pd.Series([10,20,30,40,50]) #ilk sayılar index ikinciler değerler

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
seri=pd.Series([10,20,30,40,50])

In [6]:
type(seri)

pandas.core.series.Series

In [7]:
seri.axes #seri bilgilerine ulaşıyoruz

[RangeIndex(start=0, stop=5, step=1)]

In [8]:
seri.dtype #erinin içindeki veri tipi hakkında bilgi veriir

dtype('int64')

In [9]:
seri.size #eleman sayısı

5

In [10]:
seri.ndim #boyutunu verir

1

In [11]:
seri.values #array şeklinde değerlerini getirir

array([10, 20, 30, 40, 50], dtype=int64)

In [12]:
seri.head(3) #serinin ilk 3 elemanını getirir, default olarak 5 getirir

0    10
1    20
2    30
dtype: int64

In [13]:
seri.tail(3) #head in tersi

2    30
3    40
4    50
dtype: int64

In [16]:
pd.Series([99,22,332,94,5], index=[1,3,5,7,9]) #index sayılarını kendimiz belirledik

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [17]:
pd.Series([99,22,332,94,5], index=["a", "b", "c", "d", "e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [18]:
seri1=pd.Series([99,22,332,94,5], index=["a", "b", "c", "d", "e"])

In [19]:
seri1["a"]

99

In [20]:
seri1["a":"d"] #slice işlemi

a     99
b     22
c    332
d     94
dtype: int64

In [22]:
sozluk=pd.Series({"a": 10, "b": 20, "c": 30})

In [23]:
pd.concat([seri, seri1]) #seri birleştirme

0     10
1     20
2     30
3     40
4     50
a     99
b     22
c    332
d     94
e      5
dtype: int64

<b>Eleman İşlemleri</b>

In [24]:
import numpy as np

In [25]:
a=np.array([1,22,333,4444,55555])

In [27]:
seri=pd.Series(a)
seri

0        1
1       22
2      333
3     4444
4    55555
dtype: int32

In [28]:
seri[1:3]

1     22
2    333
dtype: int32

In [31]:
seri1=pd.Series([1,56,74,36,954], index=["a", "b", "c", "d", "e"])
seri1

a      1
b     56
c     74
d     36
e    954
dtype: int64

In [33]:
seri1.index #indexleri verir

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [35]:
seri1.keys

<bound method Series.keys of a      1
b     56
c     74
d     36
e    954
dtype: int64>

In [36]:
list(seri1.items())

[('a', 1), ('b', 56), ('c', 74), ('d', 36), ('e', 954)]

In [37]:
"a" in seri1 #"a" elemanının seri içinde olup olmadığını sorguladı

True

In [38]:
seri1[["b", "c"]] #fancy index yaklaşımı

b    56
c    74
dtype: int64

In [40]:
seri1["a"]=130 #yeniden atama
seri1

a    130
b     56
c     74
d     36
e    954
dtype: int64

<b>Dataframe Oluşturma</b>

In [2]:
import pandas as pd

In [6]:
import numpy as np

In [4]:
l=[1,69,845,36,785]
l

[1, 69, 845, 36, 785]

In [5]:
pd.DataFrame(l, columns=["degisken_ismi"]) #dataframe oluşturma

degisken_ismi
0              1
1             69
2            845
3             36
4            785

In [8]:
m=np.arange(1, 10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
pd.DataFrame(m, columns=["val1", "val2", "val3"]) #numpy arrayi üzerşnden pandas çalıştırma

val1  val2  val3
0     1     2     3
1     4     5     6
2     7     8     9

In [10]:
df=pd.DataFrame(m, columns=["val1", "val2", "val3"])

In [11]:
df.head()

val1  val2  val3
0     1     2     3
1     4     5     6
2     7     8     9

In [12]:
df.columns #sütun isimlerini getirir

Index(['val1', 'val2', 'val3'], dtype='object')

In [14]:
df.columns=("deg1", "deg2", "deg3") #sütun isimlerini değiştirme
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.axes #satır ve sütun bilgilerini getirir

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [18]:
df.shape #kaça kaç olduğu

(3, 3)

In [19]:
df.ndim #boyut

2

In [20]:
df.size #kaç eleman olduğu

9

In [21]:
df.values #numpy arrayi formatını çevirir

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
type(df.values)

numpy.ndarray

<b>Eleman İşlemleri</b>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
s1=np.random.randint(10, size=5)
s2=np.random.randint(10, size=5)
s3=np.random.randint(10, size=5)

In [4]:
dic={"var1":s1, "var2":s2, "var3":s3}
dic

{'var1': array([5, 8, 6, 5, 0]),
 'var2': array([8, 7, 2, 0, 1]),
 'var3': array([0, 1, 9, 4, 2])}

In [5]:
df=pd.DataFrame(dic) #sözlük üzerinden dataframe oluşturduk
df

var1  var2  var3
0     5     8     0
1     8     7     1
2     6     2     9
3     5     0     4
4     0     1     2

In [6]:
df[0:1]

var1  var2  var3
0     5     8     0

In [7]:
df.index #indexleri getirir

RangeIndex(start=0, stop=5, step=1)

In [8]:
df.index=["a", "b", "c", "d", "e"] #index isimlendirmesini değiştirir
df

var1  var2  var3
a     5     8     0
b     8     7     1
c     6     2     9
d     5     0     4
e     0     1     2

In [9]:
df["b":"d"] 

var1  var2  var3
b     8     7     1
c     6     2     9
d     5     0     4

In [10]:
df.drop("a", axis=0) #a indeksindeki elemanı sildik, axis satırlara göre siler?

var1  var2  var3
b     8     7     1
c     6     2     9
d     5     0     4
e     0     1     2

In [11]:
df #ana yapı üzerinde değişiklik olmadı

var1  var2  var3
a     5     8     0
b     8     7     1
c     6     2     9
d     5     0     4
e     0     1     2

In [12]:
df.drop("a", axis=0, inplace=True)

In [13]:
df #eleman tamamen silinmiş oldu

var1  var2  var3
b     8     7     1
c     6     2     9
d     5     0     4
e     0     1     2

In [15]:
l=["c", "e"]

In [16]:
df.drop(l, axis=0) #fancy kullanarak verdiğimiz bir listedeki indexlerle aynı olan indexleri sildirdik

var1  var2  var3
b     8     7     1
d     5     0     4

In [17]:
"var1" in df #içinde var mı

True

In [18]:
k=["var1", "var2", "var3", "var4", "var5"]

In [19]:
for i in k:
    print(i in df) #döngü ile listedeki elelmanların olup olmadığı kontrol edildi

True
True
True
False
False


In [20]:
df["var1"] #dataframe in içindeki elemana erişme

b    8
c    6
d    5
e    0
Name: var1, dtype: int32

In [22]:
df["var4"]= df["var1"] /df["var2"] #değişken oluşturup, önceki değişkenlerin birbireine bölümünü yeni eleman olarak atadık
df

var1  var2  var3      var4
b     8     7     1  1.142857
c     6     2     9  3.000000
d     5     0     4       inf
e     0     1     2  0.000000

In [23]:
df.drop("var4", axis=1) #sütun sildik, axis 0 ise satır, 1 ise sütun olarak tanıyor

var1  var2  var3
b     8     7     1
c     6     2     9
d     5     0     4
e     0     1     2

In [24]:
df #kalıcı bir değişiklik olmadı

var1  var2  var3      var4
b     8     7     1  1.142857
c     6     2     9  3.000000
d     5     0     4       inf
e     0     1     2  0.000000

In [25]:
df.drop("var4", axis=1, inplace=True)

In [26]:
df #kalıcı olarak sildik

var1  var2  var3
b     8     7     1
c     6     2     9
d     5     0     4
e     0     1     2

In [27]:
h=["var3"]

In [28]:
df.drop(h, axis=1) #fancy ile geçici silme

var1  var2
b     8     7
c     6     2
d     5     0
e     0     1

<b>Gözlem ve Değişken Seçimi - loc ve iloc</b>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
m=np.random.randint(1,30, size=(10,3))

In [4]:
df=pd.DataFrame(m, columns=["var1", "var2", "var3"])
df

var1  var2  var3
0    26    21    25
1    22    15    10
2     7    11    19
3    10     7     3
4    15     6    13
5    16    20     9
6    24    11    13
7    18     4    14
8    15    23    17
9    25     4    25

In [5]:
df.loc[0:3] #loc seçim yapmak için kullanılır, belirtilen son indexi de dahil eder

var1  var2  var3
0    26    21    25
1    22    15    10
2     7    11    19
3    10     7     3

In [6]:
df.iloc[0:3] #iloc indexleme mantığı ile seçim yapar

var1  var2  var3
0    26    21    25
1    22    15    10
2     7    11    19

In [7]:
df.iloc[0,0]

26

In [8]:
df.iloc[:3,:2]

var1  var2
0    26    21
1    22    15
2     7    11

In [9]:
df.loc[0:3, "var3"] #3. satırı da dahil etti !!! index ismine göre seçim yaparken loc tercih edilir!!!

0    25
1    10
2    19
3     3
Name: var3, dtype: int32

In [10]:
df.iloc[0:3, 2] # !!! index rakamına göre seçimlerde iloc kullanılır!!!

0    25
1    10
2    19
Name: var3, dtype: int32

In [11]:
df.iloc[0:3]["var3"] #ve ya böyle kullanılabilir

0    25
1    10
2    19
Name: var3, dtype: int32

<b>Koşullu Eleman İşlemleri</b>

In [12]:
df

var1  var2  var3
0    26    21    25
1    22    15    10
2     7    11    19
3    10     7     3
4    15     6    13
5    16    20     9
6    24    11    13
7    18     4    14
8    15    23    17
9    25     4    25

In [13]:
df["var1"][0:2]

0    26
1    22
Name: var1, dtype: int32

In [14]:
df[0:2]

var1  var2  var3
0    26    21    25
1    22    15    10

In [15]:
df[0:2][["var1", "var2"]] #iki sütun başlığı için çift köşeli parantez!!!

var1  var2
0    26    21
1    22    15

In [16]:
df

var1  var2  var3
0    26    21    25
1    22    15    10
2     7    11    19
3    10     7     3
4    15     6    13
5    16    20     9
6    24    11    13
7    18     4    14
8    15    23    17
9    25     4    25

In [17]:
df.var1

0    26
1    22
2     7
3    10
4    15
5    16
6    24
7    18
8    15
9    25
Name: var1, dtype: int32

In [18]:
df[df.var1>15] #var1 in 15 den büyük elemanlarını getirdi

var1  var2  var3
0    26    21    25
1    22    15    10
5    16    20     9
6    24    11    13
7    18     4    14
9    25     4    25

In [19]:
df[(df.var1>15) & (df.var3<15)] #ikisi için de sağlananları getirdi

var1  var2  var3
1    22    15    10
5    16    20     9
6    24    11    13
7    18     4    14

In [21]:
df.loc[(df.var1>15), ["var1"]] #seçim işlemini loc olmadan yapınca tip hatası alıyoruz

var1
0    26
1    22
5    16
6    24
7    18
9    25

In [22]:
df[df.var1>15]["var1"] #ya da bu şekilde kullanmamız gerekir

0    26
1    22
5    16
6    24
7    18
9    25
Name: var1, dtype: int32

<b>Birleştirme İşlemleri - Join</b>

In [1]:
import numpy as np
import pandas as pd

In [2]:
m=np.random.randint(1,30, size=(5,3))

In [3]:
df1=pd.DataFrame(m, columns=["var1", "var2", "var3"])
df1

var1  var2  var3
0    17    11    19
1    15     7     1
2    19    22    27
3    19    11    12
4     5    14    11

In [4]:
df2=df1+99 #mevcut dataframe in tüm elemanlarına 99 ekler
df2

var1  var2  var3
0   116   110   118
1   114   106   100
2   118   121   126
3   118   110   111
4   104   113   110

In [5]:
pd.concat([df1,df2]) #iki df yi birleştirdi

var1  var2  var3
0    17    11    19
1    15     7     1
2    19    22    27
3    19    11    12
4     5    14    11
0   116   110   118
1   114   106   100
2   118   121   126
3   118   110   111
4   104   113   110

In [6]:
pd.concat([df1,df2], ignore_index=True) #indexlerin sıralamasını düzenledi

var1  var2  var3
0    17    11    19
1    15     7     1
2    19    22    27
3    19    11    12
4     5    14    11
5   116   110   118
6   114   106   100
7   118   121   126
8   118   110   111
9   104   113   110

In [7]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [8]:
df2.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [9]:
df2.columns=["var1", "var2", "deg3"]
df2

var1  var2  deg3
0   116   110   118
1   114   106   100
2   118   121   126
3   118   110   111
4   104   113   110

In [10]:
pd.concat([df1,df2], join="inner") #join bekirtmezsek hata alırız çünkü sütün adları farklı, sadece ortak sütunları aldı

var1  var2
0    17    11
1    15     7
2    19    22
3    19    11
4     5    14
0   116   110
1   114   106
2   118   121
3   118   110
4   104   113

In [13]:
pd.concat([df1,df2], join_axes = [df1.columns]) #istediğimiz sütunu koyduk

TypeError: concat() got an unexpected keyword argument 'join_axes'

<b>İleri Birleştirme İşlemleri</b>

In [15]:
import pandas as pd

In [27]:
df1=pd.DataFrame({"calisanlar": ["Ali", "Veli", "Ayşe", "Fatma"],
                    "grup": ["Muhasebe", "Muhendislik", "IK", "Muhendislik"]})
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayşe           IK
3      Fatma  Muhendislik

In [28]:
df2=pd.DataFrame({"calisanlar": ["Ali", "Veli", "Ayşe", "Fatma"],
                    "ilk_giris": ["2010", "2020", "2014", "2011"]})
df2

calisanlar ilk_giris
0        Ali      2010
1       Veli      2020
2       Ayşe      2014
3      Fatma      2011

In [29]:
pd.merge(df1, df2) #calisanlar ortak olduğu için birebir birleştirme yaptık

calisanlar         grup ilk_giris
0        Ali     Muhasebe      2010
1       Veli  Muhendislik      2020
2       Ayşe           IK      2014
3      Fatma  Muhendislik      2011

In [30]:
df3=pd.merge(df1, df2)
df3

calisanlar         grup ilk_giris
0        Ali     Muhasebe      2010
1       Veli  Muhendislik      2020
2       Ayşe           IK      2014
3      Fatma  Muhendislik      2011

In [31]:
df4=pd.DataFrame({ "grup": ["Muhasebe", "Muhendislik", "IK"],
                    "mudur": ["Caner", "Mustafa", "Berkcan"]})
df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           IK  Berkcan

In [32]:
pd.merge(df3, df4) #grup değerlerine birleitirildi, çoktan teke birleştirme

calisanlar         grup ilk_giris    mudur
0        Ali     Muhasebe      2010    Caner
1       Veli  Muhendislik      2020  Mustafa
2      Fatma  Muhendislik      2011  Mustafa
3       Ayşe           IK      2014  Berkcan

In [33]:
df5=pd.DataFrame({ "grup": ["Muhasebe", "Muhasebe", "Muhendislik", "Muhendislik", "IK", "IK"],
                    "yetenekler": ["matematik", "excel", "kodlama", "linux", "excel", "yonetim"]})
df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           IK      excel
5           IK    yonetim

In [34]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayşe           IK
3      Fatma  Muhendislik

In [35]:
pd.merge(df1, df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4      Fatma  Muhendislik    kodlama
5      Fatma  Muhendislik      linux
6       Ayşe           IK      excel
7       Ayşe           IK    yonetim

<b>Toplulaştırma ve Gruplama - Agreegation ve Grouping</b>

In [1]:
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.


In [4]:
?sns.load_dataset #seaborn içindeki kütüphanalere  burdan bakabiliriz

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [5]:
df=sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [6]:
df.shape #1035 gözlem ve 6 değişkenden oluşuyor

(1035, 6)

In [7]:
df.mean() #tüm değişkenlerin ortalama değerlerini verdi

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [8]:
df["mass"].mean() #belli bir değişkeni getirmek istiyırsak

2.6381605847953216

In [9]:
df["mass"].count() #içindeki değerleri saydı

513

In [10]:
df["mass"].min() #min değeri getirdi

0.0036

In [11]:
df["mass"].sum() #değişkenlerin değerlerini topladı

1353.37638

In [12]:
df["mass"].std() #standart sapma

3.8186166509616046

In [13]:
df["mass"].var() #varyans

14.58183312700122

In [14]:
df.describe() #df deki tüm istatistikleri getirdi

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [16]:
df.describe().T #transpozunu aldı

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [17]:
df.dropna().describe() #eksik değerleri sildii

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

<b>Gruplama İşlemleri</b>

In [19]:
import pandas as pd

In [20]:
df=pd.DataFrame({ "gruplar": ["A", "B", "C", "A", "B", "C"],
                    "veri": [10,11,52,23,43,55]}, columns=["gruplar", "veri"])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [21]:
df.groupby("gruplar")

In [22]:
df.groupby("gruplar").mean() #ortalama aldı

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [23]:
df=sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [25]:
df.groupby("method")["orbital_period"].mean() #değişkenleri methodlarına göre grupladı, orbital_period değerlerini aldı, bu değerlerin ortalamasını getirdi

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [26]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

<b>İleri Toplulaştırma İşlemleri - Aggregate</b>

In [32]:
import pandas as pd
import numpy as np

In [29]:
df=pd.DataFrame({ "gruplar": ["A", "B", "C", "A", "B", "C"],
                    "degisken1": [10,11,52,23,43,55],
                    "degisken2": [100,523,658,963,458,236]},
               columns=["gruplar", "degisken1", "degisken2"])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         11        523
2       C         52        658
3       A         23        963
4       B         43        458
5       C         55        236

In [31]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.5      531.5
B             27.0      490.5
C             53.5      447.0

In [34]:
df.groupby("gruplar").aggregate([min, np.median, max]) #istenilen matematiksel fonk. hesaplayıp yazdırdı

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.5  23       100  531.5  963
B              11   27.0  43       458  490.5  523
C              52   53.5  55       236  447.0  658

In [35]:
df.groupby("gruplar").aggregate({"degisken1": min, "degisken2": max})

degisken1  degisken2
gruplar                      
A               10        963
B               11        523
C               52        658

<b>Filter</b>

In [37]:
df=pd.DataFrame({ "gruplar": ["A", "B", "C", "A", "B", "C"],
                    "degisken1": [10,11,52,23,43,55],
                    "degisken2": [100,523,658,963,458,236]},
               columns=["gruplar", "degisken1", "degisken2"])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         11        523
2       C         52        658
3       A         23        963
4       B         43        458
5       C         55        236

In [40]:
def filter_func(x):
    return x["degisken1"].std()>9 #standart sapması 9 dan büyük olan değişken 1 leri getirdi

In [41]:
df.groupby("gruplar").filter(filter_func) #filter e yardımcı oldu

gruplar  degisken1  degisken2
0       A         10        100
1       B         11        523
3       A         23        963
4       B         43        458

<b>Transform</b>

In [2]:
import pandas as pd

In [14]:
import numpy as np

In [3]:
df=pd.DataFrame({ "gruplar": ["A", "B", "C", "A", "B", "C"],
                    "degisken1": [10,11,52,23,43,55],
                    "degisken2": [100,523,658,963,458,236]},
               columns=["gruplar", "degisken1", "degisken2"])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         11        523
2       C         52        658
3       A         23        963
4       B         43        458
5       C         55        236

In [4]:
df["degisken1"]*9 #tüm elemanları 9 ile çarptı

0     90
1     99
2    468
3    207
4    387
5    495
Name: degisken1, dtype: int64

In [8]:
df1=df.iloc[:,1:3]

In [10]:
df1.transform(lambda x: (x-x.mean()) /x.std()) 
# x ile değşkenlerin kendisi-ortalaması işlemini tüm değişkenlere uyguladık ve standart sapmaya böldük

degisken1  degisken2
0  -1.101533  -1.270032
1  -1.052210   0.108643
2   0.970006   0.548645
3  -0.460342   1.542725
4   0.526105  -0.103210
5   1.117974  -0.826770

<b>Apply</b>

In [11]:
import pandas as pd

In [13]:
df=pd.DataFrame({ "degisken1": [10,11,52,23,43,55],
                "degisken2": [100,523,658,963,458,236]},
               columns=[ "degisken1", "degisken2"])
df

degisken1  degisken2
0         10        100
1         11        523
2         52        658
3         23        963
4         43        458
5         55        236

In [15]:
df.apply(np.sum) #toplamlarını getirdi

degisken1     194
degisken2    2938
dtype: int64

In [16]:
df.apply(np.mean) #ortalamalarını aldı

degisken1     32.333333
degisken2    489.666667
dtype: float64

In [17]:
df1=pd.DataFrame({ "gruplar": ["A", "B", "C", "A", "B", "C"],
                    "degisken1": [10,11,52,23,43,55],
                    "degisken2": [100,523,658,963,458,236]},
               columns=["gruplar", "degisken1", "degisken2"])
df1

gruplar  degisken1  degisken2
0       A         10        100
1       B         11        523
2       C         52        658
3       A         23        963
4       B         43        458
5       C         55        236

In [19]:
df1.groupby("gruplar").apply(np.mean) #gruplar sütununa göre grupladı ve değerlerin otalamalarını yazdırdı

degisken1  degisken2
gruplar                      
A             16.5      531.5
B             27.0      490.5
C             53.5      447.0

<b>Pivot Tablolar</b>

In [2]:
import pandas as pd

In [3]:
import seaborn as sns

In [4]:
titanic=sns.load_dataset("titanic")
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [5]:
titanic.groupby("sex")[["survived"]].mean() #cinsiyetleri grupladı ve hayatta kalma ortalamalarını getirdi
#dataframe olmasını istersek iki parantez koymamız gerekir

survived
sex             
female  0.742038
male    0.188908

In [7]:
titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean")

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [8]:
titanic.pivot_table("survived", index="sex", columns="class") #index satır, column sütun olarak kabul ediyor

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [10]:
age=pd.cut(titanic["age"], [20,50,90]) #sürekli bir değişkeni kategorik bir değişken yapmış olduk, yaş aralıklarını getirdi
age.head(10)

0    (20.0, 50.0]
1    (20.0, 50.0]
2    (20.0, 50.0]
3    (20.0, 50.0]
4    (20.0, 50.0]
5             NaN
6    (50.0, 90.0]
7             NaN
8    (20.0, 50.0]
9             NaN
Name: age, dtype: category
Categories (2, interval[int64]): [(20, 50] < (50, 90]]

In [11]:
titanic.pivot_table("survived", ["sex", age], "class") #age ifadesini dışarıdan aldığımız için tırnak koymadık

class               First    Second     Third
sex    age                                   
female (20, 50]  0.965517  0.909091  0.407407
       (50, 90]  1.000000  0.666667  1.000000
male   (20, 50]  0.455882  0.058824  0.136905
       (50, 90]  0.192308  0.083333  0.000000

<b>Dış Kaynaklı Veri Okuma</b>

In [1]:
import pandas as pd

In [2]:
pd.read_csv("reading_data/ornekcsv.csv", sep=";") #sep ile aralardaki ; ü kaldırdık, dosyayı verimanüpülasyonu dosyasına ekledik
#sep koymadan aralara ; koydu csv dosyası olduğu için

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [3]:
pd.read_csv("reading_data/duz_metin.txt") #text okuma, düz metinlerde boşluk bıraksak da okunabilir

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [4]:
pd.read_excel("reading_data/ornekx.xlsx") #excel okuma 

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [5]:
df=pd.read_excel("reading_data/ornekx.xlsx")

In [6]:
type(df) #dataframe olarak oluşuyor

pandas.core.frame.DataFrame

In [8]:
df.columns=("A", "B", "C") #sütun başlıklarını değiştirdik
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0